[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contracts = "FPqGhJFbRbR5hMWw3UsLMQ4G7QgJDJFGKZHTRtHg1tXY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/toastx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
